# Language and versions:
language: python
python:
  - "3.7"
  - "3.8"

# Command to install dependencies:
install:
  - pip install -r requirements.txt

# Command to run pytests:
script: python setup.py develop && pytest
